### PR TITLE
Reset MFC decoder if the frame rate for 2s dropps under 40

### PR DESCRIPTION
**Pull request by catalinii**
Hi,

I am using LiveTV and sometimes the stream corrupts the MFC decoder (the problem is the stream). At that point I have noticed that the frame rate drops below 25 even the stream becomes ok after that. I have made this patch that detects if the frame rate for 2 seconds drops under 40 and if so, reset the MFC decoder, which fixes the issue.

Thanks

### CODE REVIEW

**Comment by marlemion** [comment]
I tried this patch yesterday and it significantly improves my Live TV experience on my odroid U2 (DVB-S2 via USB). Said that, the MFC does not reset itself if some frames are corrupted, what happens sometimes in the stream even though the signal quality is >95%.

The only problem I still have is that there are two states of playback:

1) everything is smooth, no skipped frames, no dropped frames. Only very rarely there are some problems, but with the patch the MFC does not reset.

2) the MFC drops frames, the picture looks like it tries to play the frames in the wrong order, i.e. the picture 'jumps' forward and backward.

Please note that these states are observable in one identical stream!

Without the patch, the MFC resets very often and it can happen that on each reset the state of playback switches from 1 to 2 or from 2 to 1. It happens very often that directly after initializing a channel, state 2 is reached. With the patch it takes some time during state 2 until the MFC finally resets and hopefully the state of playback reaches state 1 after the reset. If it did, the stream can be watched flawlessly for hours.

So there seems to be a need for a check of order of frames or maybe a quick reset of the MFC when being in state 2.

**Comment by catalinii** [comment]
Hi,

Check if this patch that works better for you, its what I am using now for livetv. Its an older version of the mfc decoder and is also for the patched hybris version. You use the hybris code from here for non patches version.

The patch works with the original kodi 15.*

https://github.com/catalinii/kodi_patch_odroid_xu

**Comment by marlemion** [comment]
Would that patch work for U2/U3, too?

**Comment by catalinii** [comment]
My patch does not work for u2/u3, but probably you can make it work as the mfc code is the same ( just an older version).

**Comment by marlemion** [comment]
Well I 'extracted' the following patch, which doesn't seem to do the trick:

``` c++
--- a/xbmc/cores/dvdplayer/DVDCodecs/Video/DVDVideoCodecMFC.cpp
+++ b/xbmc/cores/dvdplayer/DVDCodecs/Video/DVDVideoCodecMFC.cpp
@@ -212,6 +212,9 @@ bool CDVDVideoCodecMFC::Open(CDVDStreamInfo &hints, CDVDCodecOptions &options) {
   m_bDropPictures = false;
   memzero(m_videoBuffer);

+  dtime = 2000 + XbmcThreads::SystemClockMillis();  // start 2s after init
+  sec = m_reset = 0;
+
   if (!OpenDevices()) {
     CLog::Log(LOGERROR, "%s::%s - No Exynos MFC Decoder/Converter found", CLASSNAME, __func__);
     return false;
@@ -445,6 +448,13 @@ int CDVDVideoCodecMFC::Decode(BYTE* pData, int iSize, double dts, double pts) {
   if (m_hints.ptsinvalid)
     pts = DVD_NOPTS_VALUE;

+  if (m_reset) {
+        m_reset = 0;
+        Reset();                                                                               
+        dtime = XbmcThreads::SystemClockMillis();                                              
+  }                                                                                            
+                                                                                               
+                                                                                               
   //unsigned int dtime = XbmcThreads::SystemClockMillis();                                     
   debug_log(LOGDEBUG, "%s::%s - input frame iSize %d, pts %lf, dts %lf", CLASSNAME, __func__, iSize, pts, dts);                                                                                

@@ -550,6 +560,15 @@ void CDVDVideoCodecMFC::Reset() {                                          
 }                                                                                              

 bool CDVDVideoCodecMFC::GetPicture(DVDVideoPicture* pDvdVideoPicture) {
+  unsigned int ctime = XbmcThreads::SystemClockMillis();
+  if ((int ) (ctime - dtime) > 2500 ) dtime = ctime;  //do not reset when pausing
+  else if ((int ) (ctime - dtime) > 2000) {
+         CLog::Log(LOGDEBUG, "%s::%s - GetPicture dtime = %ld, ctime = %ld, fp2s = %d ", CLASSNAME, __func__,dtime, ctime, fp2s);
+        dtime = ctime;
+        if( sec < 30 ) m_reset = 1;
+        sec = 0;
+  }
+  sec++;

   *pDvdVideoPicture = m_videoBuffer;
   debug_log(LOGDEBUG, "%s::%s - output frame pts %lf", CLASSNAME, __func__, m_videoBuffer.pts);
--- a/xbmc/cores/dvdplayer/DVDCodecs/Video/DVDVideoCodecMFC.h
+++ b/xbmc/cores/dvdplayer/DVDCodecs/Video/DVDVideoCodecMFC.h
@@ -41,6 +41,9 @@ class CDVDVideoCodecMFC : public CDVDVideoCodec

   bool m_bCodecHealthy;

+  long int dtime;
+  int m_reset, sec;
+
   V4l2Device *m_iDecoderHandle;
   V4l2Device *m_iConverterHandle;

```

**Comment by marlemion** [comment]
My current patch is:

``` c++
--- a/xbmc/cores/dvdplayer/DVDCodecs/Video/DVDVideoCodecMFC.cpp
+++ b/xbmc/cores/dvdplayer/DVDCodecs/Video/DVDVideoCodecMFC.cpp
@@ -212,6 +212,9 @@ bool CDVDVideoCodecMFC::Open(CDVDStreamInfo &hints, CDVDCodecOptions &options) {
   m_bDropPictures = false;
   memzero(m_videoBuffer);

+  dtime = 10000 + XbmcThreads::SystemClockMillis();  // start 10s after init
+  fp2s = m_reset = 0;
+
   if (!OpenDevices()) {
     CLog::Log(LOGERROR, "%s::%s - No Exynos MFC Decoder/Converter found", CLASSNAME, __func__);
     return false;
@@ -445,6 +448,13 @@ int CDVDVideoCodecMFC::Decode(BYTE* pData, int iSize, double dts, double pts) {
   if (m_hints.ptsinvalid)
     pts = DVD_NOPTS_VALUE;

+  if (m_reset) {
+        m_reset = 0;
+        Reset();
+        dtime = XbmcThreads::SystemClockMillis();
+  }
+
+
   //unsigned int dtime = XbmcThreads::SystemClockMillis();
   debug_log(LOGDEBUG, "%s::%s - input frame iSize %d, pts %lf, dts %lf", CLASSNAME, __func__, iSize, pts, dts);

@@ -550,6 +560,18 @@ void CDVDVideoCodecMFC::Reset() {
 }

 bool CDVDVideoCodecMFC::GetPicture(DVDVideoPicture* pDvdVideoPicture) {
+  long int ctime = XbmcThreads::SystemClockMillis();
+  if ( ctime - dtime > 2500 ) dtime = ctime;  //do not reset when pausing
+  else if ( ctime - dtime > 2000) {
+         CLog::Log(LOGDEBUG, "%s::%s - GetPicture dtime = %ld, ctime = %ld, fp2s = %d ", CLASSNAME, __func__,dtime, ctime, fp2s);
+        dtime = ctime;
+        if( fp2s < 30 ){  
+               m_bCodecHealthy = false;; // if the average for the last 2 seconds is less than 40 frames, Reset
+               m_reset = 1;
+       }
+        fp2s = 0;
+  }
+  fp2s++;

   *pDvdVideoPicture = m_videoBuffer;
   debug_log(LOGDEBUG, "%s::%s - output frame pts %lf", CLASSNAME, __func__, m_videoBuffer.pts);
--- a/xbmc/cores/dvdplayer/DVDCodecs/Video/DVDVideoCodecMFC.h
+++ b/xbmc/cores/dvdplayer/DVDCodecs/Video/DVDVideoCodecMFC.h
@@ -41,6 +41,9 @@ class CDVDVideoCodecMFC : public CDVDVideoCodec

   bool m_bCodecHealthy;

+  long int dtime;
+  int m_reset, fp2s;
+
   V4l2Device *m_iDecoderHandle;
   V4l2Device *m_iConverterHandle;

```

**Comment by catalinii** [comment]
Hi, are you saying this patch is not working for you ?

**Comment by marlemion** [comment]
Hey, the first, which I 'extracted' does not work. The second, which is actually the one you initially posted in this thread does work (I changed it to > 30 fps).

The main difference is in CDVDVideoCodecMFC::GetPicture I guess.

**Pull request closed without merging**
