### PR TITLE
X11/GLES platform + MFC/FIMC support

### PR DESCRIPTION
**Pull request by stsichler**
Hi Owersun,
are you interested in this? 
It is a resurrection of the X11/GLES platform, which is required to get Kodi Leia rendering again in appropriate speed on my good old ODROID-U3 with Ubuntu 16.04. 

In addition, it also contains another 2 fixes required for the ARM platform:
The changes in DVDInputStreamNavigator.cpp prevent a compilation failure because of an out-of-range branch jump.
The changes in SortUtils.cpp prevent a crash when accessing the database.

note: the "HACK! DONT MERGE ME!" commit is fixed by ac1f4c682456a2f55dce3768ccb98e91dde0f99e.

### CODE REVIEW

**Comment by Owersun** [comment]
Hey!
I see this massive amount of changes split.
There are two different things in here, adding back X11-EGL and making MFC work.
I'm not sure I want X11-EGL, this is not something I was dealing with in this repo, and MFC changes are brutally chopped to work only for -U3, and most people use -XU4 now.
If you don't mind I would pick your changes in blocks and test them and implement stuff the way that your changes are going to be authored by you in the end.

**Comment by stsichler** [comment]
I split the changes already and merged them freshly into a clean repo. So it's now only a few commits left and they are clearly seperated by feature. See attachment.
I believe this makes it much easier.

[kodi-18-patches.zip](https://github.com/Owersun/xbmc/files/3307975/kodi-18-patches.zip)

(maybe you're only interested in patch 0006 in the zip...)

**Comment by stsichler** [comment]
regarding XU4, please also note my commits d73eea134db6428fe15e74626d6d69f13e0cecdb and 2223fd27469bf1acedbe6a504b8d7ce6ed6baf97.

**Comment by Owersun** [comment]
Thank you for patches, as I've said most probably I'm going to port my changes to Leia manually first, and then start adding your changes step by step, like neon tiled picture converter to untiled, etc., in chunks and see how stuff works.
I really don't know when there is going to be even first version of that in the repo, unfortunately I don't have much time for that now. But I guess it's going to be different from all the changes you do (less modification) judging by what I see you are changing. So first of all thank you for picking this up and thank you for updating it on your side.

PS. I can tell you why do I prefer to do as few changes to what it is now as possible, - it is because the thing developed in at least two years. And in these two years I rewrote it two or three times completely. There are so many experiments there it's unbelievable, at some point I had a folder with 20+ videos, people were sending me that "doesn't play properly", it was my unittesting folder for modifications. I went through all what you are trying to do now, more buffers, less buffers, locked buffers for display, and much more. I stopped at the point when everything worked. It's really measured process there that not only fits something I watch. I would first try to make it work as it is.

**Comment by stsichler** [comment]
NOTE: I now commited what I sent you as patches into a new branch Leia-odroid-u3 in my fork.

**Pull request closed without merging**
